package ru.creditbot.bot;

public enum UserState {

    NONE,

    WAITING_FOR_AMOUNT,
    WAITING_FOR_MONTHS,
    WAITING_FOR_INTEREST_RATE,
    WAITING_FOR_PAYMENT_TYPE,

    WAITING_FOR_MANAGER_LOGIN,
    WAITING_FOR_MANAGER_PASSWORD,

    WAITING_FOR_FILTER_MIN_AMOUNT,
    WAITING_FOR_FILTER_MAX_AMOUNT,
    WAITING_FOR_FILTER_PAYMENT_TYPE
}